// Generated by CoffeeScript 1.12.2
(function() {
  var reverse, s;

  reverse = function(s) {
    if (s.length < 2) {
      return s;
    } else {
      return reverse(s.slice(1)) + s[0];
    }
  };

  s = "HelloWorld";

  console.log("s=" + s + ", s.reverse=" + (reverse(s)));

}).call(this);
