# Given two strings s and t which consist of only lowercase letters.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Find the letter that was added in t.

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        #   made two histograms of each string. Saw wich characters didn't repeat the same ammount of times.
        #   pretty striaght forward, but the runtime would be better if I used a dictionary. Oh well :/

        sList = list(s)
        tList = list(t)
        for rm in sList:
            tList.remove(rm)
        # print(tList[0])
        return tList[0]
